org.gradle.caching=true
#org.gradle.unsafe.configuration-cache=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.warning.mode=all
# Gradle Settings
org.gradle.jvmargs=-XX:MaxMetaspaceSize=2g
org.gradle.parallel=true
# Kotlin Settings
kotlin.code.style=official
kotlin.incremental=true
kapt.use.worker.api=true
kapt.incremental.apt=true
# Compiler JVM
javaVersion=25
#=======================================================================================================================
# Project Identity — Single Source of Truth
group=com.ntt
version=0.0.1-SNAPSHOT
